### ISSUE TITLE
Predict the None

### ISSUE THREAD

**Issue by wangtvb** [kulbachcedric/EvOAutoML#6]
Hi Cedric:

I used the official example and run this dataset 'datasets.Phishing()' using the EvolutionaryBaggingClassifier().

But I don't know why the first instance, this pipeline predicts that it is None. Is it normal?

<img width="1231" alt="Screenshot 2022-12-04 at 14 09 12" src="https://user-images.githubusercontent.com/44760380/205495432-2da27e5d-9c9f-4310-8ca7-ce93776d8b58.png">

**Comment by kulbachcedric** [comment]
Hi @wangtvb,

thanks for sharing the issue. 
I'll have a look into that and open a new branch. 
Hope to have it fixed until the end of the week.

Best
Cedric

**Comment by wangtvb** [comment]
Hi Cedric:

I think if some algorithms don't have the instance at the beginning, they could not predict the first instance at the beginning. Taking the KNN as a example, the window used in KNN at the beginning is empty.  The first instance is used to predict, and it may predict the None. This is because the window at the beginning doesn't have any values, it leads to None. But i am not sure, it might be the one of the reasons.

**Comment by kulbachcedric** [comment]
> Hi Cedric:
> 
> I think if some algorithms don't have the instance at the beginning, they could not predict the first instance at the beginning. Taking the KNN as a example, the window used in KNN at the beginning is empty. The first instance is used to predict, and it may predict the None. This is because the window at the beginning doesn't have any values, it leads to None. But i am not sure, it might be the one of the reasons.

Hi Jason,

I finally had a look into the first `None` value. Actually the problem lies within the river Bagging classifier. The `predict_one` function calls the `predict_proba_one` function of the base estimator. The first result of the `predict_proba_one` function is actually an empty dict as no class is known to the estimator, which causes the output to be `None`. 

It may be possible to re-implement the bagging estimators in such a way that the `predict_one` function can do without the `predict_proba_one` function.

Best 
Cedric

**Comment by zhaoyangwang-research** [comment]
Hi Cedric:

Thank you for solving this problem. 

Best 
Jason
